### ISSUE TITLE
使用出错

### ISSUE THREAD

**Issue by wang0168** [mcxtzhang/ItemDecorationIndexBar#1]
Process: tts.project.orange.meike, PID: 23132
 java.lang.ArithmeticException: divide by zero
 at tts.project.slidelib.IndexBar.widget.IndexBar.onSizeChanged(IndexBar.java:232)
求解

**Comment by wang0168** [comment]
setAdapter() 时 如果 数据源为空 就会出现上述错误

**Comment by wang0168** [comment]
indexBar.setmPressedShowTextView(tvSideBarHint)//设置HintTextView
                .setNeedRealIndex(false)//设置需要真实的索引
                .setmLayoutManager(mManager)//设置RecyclerView的LayoutManager
                .setmSourceDatas(mData);//设置数据源 


如果mData  size  =0  就会出现 上述错误

**Comment by mcxtzhang** [comment]
2016 09 08 已修复bug，对空数据 进行了判断

**Comment by wang0168** [comment]
怎么配合 adapter.notifyDataSetChanged() 去刷新数据？

**Comment by wang0168** [comment]
@mcxtzhang 怎么配合adapter.notifyDataSetChanged()  去刷新数据

**Comment by mcxtzhang** [comment]
试试用 .setmSourceDatas(mData);//设置数据源  设置新的数据源进去呀
