### ISSUE TITLE
去掉悬停

### ISSUE THREAD

**Issue by cloudpluie** [mcxtzhang/ItemDecorationIndexBar#10]
怎么去掉悬停呀，把TitleItemDecoration的onDrawOver方法删掉以后，每次title滑动到顶部时，会变成白色，把头部标题遮盖掉？

**Comment by mcxtzhang** [comment]
加个 if else 判断，

**Comment by cloudpluie** [comment]
在哪儿加呀？我想去掉悬停的标题，但是把TitleItemDecoration的onDrawOver方法删掉以后，每次title滑动到顶部时，那个标题的item会被白色覆盖。

**Comment by mcxtzhang** [comment]
我把自带的三个Demo里的onDrawOver 方法注释后，一切正常。 没有悬停，效果也正常。
