### ISSUE TITLE
DividerItemDecoration设计多余

### ISSUE THREAD

**Issue by zhangls2014** [mcxtzhang/ItemDecorationIndexBar#3]
其实，不用区分屏幕的横竖，都能正确的绘制分割线，反而区分后横屏的时候绘制的是垂直于屏幕最长边的分割线；而且，方向不应该使用LinearLayoutManager.HORIZONTAL这种方式指定，应该根据系统屏幕方向设置，更灵活

**Comment by mcxtzhang** [comment]
首先你需要知道，DividerItemDecoration中的参数 不是屏幕的横竖，而是LinearLayoutManager的横竖，和系统屏幕方向无关。
而且此类是Google官方提供，这里仅仅是用来作为提现可添加多个Decoration的示例。
